### PR TITLE
First commit of new code base. AGR-2117

### PR DESCRIPTION
**Pull request by christabone**

### CODE REVIEW

**Comment by christabone** [comment]
The code itself needs some re-writing. It's a bit clunky. The process does work, however.

**Comment by christabone** [comment]
Updated title to include AGR-2117 for the new ticket.

**Comment by azurebrd** [comment]
Description : 
Adapts agr_loader code to pull latest files from FMS, which have been uploaded by agr_ferret and DQMs.  Then in parallel creates molecular interaction and genetic interaction files, and uploads them to FMS for a release snapshot and agr_loader to use.

**Comment by christabone** [comment]
@azurebrd I made some minor changes -- if you have a chance to review them, that would be great. Otherwise I think we're good to merge. We can revisit and streamline later if necessary.

**Review by azurebrd — APPROVED** [review]
Cool, looks great !  I haven't ran it to test it still works, but if you have, please merge it :)

**Pull request merged**
